version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-network

volumes:
  postgres_data:
    driver: local

networks:
  prisma-network:
    driver: bridge
